CONFIG_NAME: interop
PRESET_BASE: interop

GENESIS_FORK_VERSION: 0x20000089

ALTAIR_FORK_EPOCH: 0
ALTAIR_FORK_VERSION: 0x20000090

BELLATRIX_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x20000091
TERMINAL_TOTAL_DIFFICULTY: 0

CAPELLA_FORK_EPOCH: 0
CAPELLA_FORK_VERSION: 0x20000092
MAX_WITHDRAWALS_PER_PAYLOAD: 16

DENEB_FORK_VERSION: 0x20000093

ELECTRA_FORK_VERSION: 0x20000094

SECONDS_PER_SLOT: 10
SLOTS_PER_EPOCH: 6

DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242
